name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install PortAudio
      run: brew install portaudio

    - name: Build project for macOS
      run: make

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
