name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: macos-latest-large

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache Homebrew packages
      uses: actions/cache@v2
      with:
        path: ~/Library/Caches/Homebrew
        key: brew-packages-${{ runner.os }}-${{ hashFiles('**/Brewfile.lock.json') }}
        restore-keys: |
          brew-packages-${{ runner.os }}-

    - name: Install PortAudio
      run: brew install portaudio

    - name: Build project for macOS
      run: make

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
